# Generated by Django 2.0.3 on 2020-07-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ricauser',
            old_name='id_pasport_expiry_date',
            new_name='id_passport_expiry_date',
        ),
    ]
