# Generated by Django 2.0.3 on 2020-07-28 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200726_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricauser',
            name='id',
        ),
        migrations.AlterField(
            model_name='ricauser',
            name='mobile_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
