# Generated by Django 2.0.3 on 2020-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200728_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricauser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ricauser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
