# Generated by Django 2.0.3 on 2020-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200731_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RicaOfficer',
            fields=[
                ('mobile_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('mobile_number', 'name'),
            },
        ),
        migrations.DeleteModel(
            name='RicaUser',
        ),
    ]
