# Generated by Django 2.0.3 on 2020-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200805_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('mobile_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('id_passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_passport_expiry_date', models.DateField(blank=True, null=True)),
                ('photo_of_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_of_proof', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
