# Generated by Django 2.0.3 on 2020-08-19 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200805_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricacustomer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subagent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
