# Generated by Django 2.0.3 on 2020-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200819_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricacustomer',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ricacustomer',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ricacustomer',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
    ]
